-- Schema migration: add columns for 5-strategy indicator set
-- Run against Supabase SQL editor or via psql

ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS sma_50 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS sma_100 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS sma_200 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS ema_50 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS ema_100 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS ema_200 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS macd DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS macd_signal DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS macd_hist DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS adx_14 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS stoch_k DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS stoch_d DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS session_vwap DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_upper_1_5 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_upper_2 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_lower_1_5 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_lower_2 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_upper_2_5 DOUBLE PRECISION;
ALTER TABLE fx_candles ADD COLUMN IF NOT EXISTS vwap_lower_2_5 DOUBLE PRECISION;
